#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)] // test code: helpers panic on purpose
//! Fitting oracle for the models without one before (task T-029): `pk1.iv_infusion`,
//! `pk1.oral_0` (zero-order input) and `pk1.oral_1_lag` (first-order absorption with a lag),
//! five weightings each. The reference fits are `oracle/expected/fit/fit_{infusion,zero_order,lag}_*`,
//! produced by `oracle/scripts/fit_wls.R` (`minpack.lm::nlsLM`, checked against `stats::nls`; the
//! statistics from the formulas of `specs/fit.md` section 7) on synthetic profiles generated by the
//! same script from the closed forms of `specs/models.md` with a fixed seed and log-normal noise
//! (the options file of each case says how). The duration `dur` of the infusion and of the
//! zero-order input is a fixed parameter in both the reference and the engine.
//!
//! Written before the engine could pass them (task T-029); no test is ignored. The engine has no
//! closed-form partial derivatives for these three models yet (`caladrius-fit` `model.rs` has them
//! for `pk1.iv_bolus` and `pk1.oral_1` only), and the reference statistics were computed with
//! analytic derivatives, so each case has three kinds of test:
//!
//! - `analytic_*` (seven per case, the groups of `oracle_fit.rs`): the engine's algorithm and
//!   statistics through `run_model`, with a `FitModel` written in this file that delegates the
//!   predictions to `caladrius-models` and supplies closed-form partial derivatives (an
//!   independent derivation, checked against central differences below). These test the
//!   optimizer, the weights and the statistics for the new models at the contract tolerances.
//! - `the_engine_has_closed_form_derivatives_for_*` (one per model): the engine as shipped, `run`
//!   with `Derivatives::Analytic`, on every case of the model: convergence and the six value groups
//!   of the `analytic_*` tests. They fail with `AnalyticDerivativesUnavailable` until the engine
//!   gains the closed forms for the model (card T-030), and then compare the shipped path with R.
//! - `forward_difference_converges`: the engine as shipped with its default derivatives converges.
//!   Its estimates are not compared with the exact minimum here: forward differences stop at a
//!   point that differs from it by the error of the increment, which is also true of the older
//!   models (`specs/differences.md` D-03).
//!
//! The tolerances are those of `caladrius-testkit` and are not touched.

mod common;

use std::collections::BTreeMap;

use caladrius_fit::{Derivatives, FitError, FitInput, FitModel, FitResult, Secondary, run_model};
use caladrius_models::{ModelError, ModelId};
use common::{Runner, check_group, check_status, engine};

// ---------------------------------------------------------------- closed-form derivatives

/// A model of `caladrius-models` with closed-form partial derivatives written for this test.
struct WithClosedForms(ModelId);

/// d C / d `name` at time `t`, `None` for a parameter that is not differentiated (`dur` is fixed).
fn partial(
    model: ModelId,
    dose: f64,
    p: &BTreeMap<String, f64>,
    name: &str,
    t: f64,
) -> Option<f64> {
    let get = |n: &str| p.get(n).copied();
    match model {
        ModelId::IvInfusion | ModelId::Oral0 => {
            // C = D/(T V k) (1 - e^(-k t)) for t <= T, then C(T) e^(-k (t - T)).
            let (v, k, big_t) = (get("v")?, get("k")?, get("dur")?);
            let r0 = dose / big_t;
            let c = if t <= big_t {
                r0 / (v * k) * (1.0 - (-k * t).exp())
            } else {
                r0 / (v * k) * (1.0 - (-k * big_t).exp()) * (-k * (t - big_t)).exp()
            };
            match name {
                "v" => Some(-c / v),
                "k" if t <= big_t => {
                    Some(r0 / v * (k * t * (-k * t).exp() - (1.0 - (-k * t).exp())) / (k * k))
                }
                "k" => {
                    let e = (-k * big_t).exp();
                    Some(c * (-1.0 / k + big_t * e / (1.0 - e) - (t - big_t)))
                }
                _ => None,
            }
        }
        ModelId::Oral1Lag => {
            let (v, k, ka, tlag) = (get("v")?, get("k")?, get("ka")?, get("tlag")?);
            let s = t - tlag;
            if s <= 0.0 {
                return Some(0.0);
            }
            let b = dose * ka / (v * (ka - k));
            let f = b * ((-k * s).exp() - (-ka * s).exp());
            match name {
                "v" => Some(-f / v),
                "k" => Some(-b * s * (-k * s).exp() + f / (ka - k)),
                "ka" => Some(b * s * (-ka * s).exp() - f * k / (ka * (ka - k))),
                "tlag" => Some(b * (k * (-k * s).exp() - ka * (-ka * s).exp())),
                _ => None,
            }
        }
        _ => None,
    }
}

impl FitModel for WithClosedForms {
    fn predict(
        &self,
        dose: f64,
        params: &BTreeMap<String, f64>,
        times: &[f64],
    ) -> Result<Vec<f64>, ModelError> {
        self.0.predict(dose, params, times)
    }

    fn analytic_derivatives(
        &self,
        dose: f64,
        params: &BTreeMap<String, f64>,
        times: &[f64],
        names: &[String],
    ) -> Option<Vec<Vec<f64>>> {
        names
            .iter()
            .map(|name| {
                times
                    .iter()
                    .map(|&t| partial(self.0, dose, params, name, t))
                    .collect::<Option<Vec<f64>>>()
            })
            .collect()
    }

    fn secondary(&self, dose: f64, params: &BTreeMap<String, f64>) -> Vec<Secondary> {
        self.0.secondary(dose, params)
    }
}

/// The engine's algorithm with the test-side closed forms.
fn with_closed_forms(input: &FitInput) -> Result<FitResult, FitError> {
    run_model(&WithClosedForms(input.model), input)
}

const WITH_CLOSED_FORMS: Runner = with_closed_forms;

/// The closed forms written above agree with central differences of the model itself, so that a
/// slip in them cannot pass for an engine disagreement.
#[test]
fn the_closed_form_derivatives_match_central_differences() {
    type Case<'a> = (ModelId, &'a [(&'a str, f64)], &'a [f64]);
    let cases: [Case; 3] = [
        (
            ModelId::IvInfusion,
            &[("v", 15.0), ("k", 0.25), ("dur", 2.0)],
            &[0.5, 1.0, 1.9, 2.1, 4.0, 12.0],
        ),
        (
            ModelId::Oral0,
            &[("v", 40.0), ("k", 0.15), ("dur", 3.0)],
            &[0.5, 2.9, 3.1, 6.0, 24.0],
        ),
        (
            ModelId::Oral1Lag,
            &[("v", 30.0), ("k", 0.12), ("ka", 1.2), ("tlag", 0.5)],
            &[0.75, 1.0, 2.0, 8.0, 24.0],
        ),
    ];
    for (model, params, times) in cases {
        let p: BTreeMap<String, f64> = params.iter().map(|(n, v)| (n.to_string(), *v)).collect();
        for (name, value) in params {
            if *name == "dur" {
                continue;
            }
            let h = 1e-6 * value;
            let mut up = p.clone();
            let mut down = p.clone();
            up.insert(name.to_string(), value + h);
            down.insert(name.to_string(), value - h);
            let fu = model.predict(100.0, &up, times).unwrap();
            let fd = model.predict(100.0, &down, times).unwrap();
            for (i, &t) in times.iter().enumerate() {
                let numeric = (fu[i] - fd[i]) / (2.0 * h);
                let closed = partial(model, 100.0, &p, name, t).unwrap();
                assert!(
                    (closed - numeric).abs() <= 1e-6 * (1e-3 + numeric.abs()),
                    "{model:?} d/d{name} at t = {t}: {closed} against {numeric}"
                );
            }
        }
    }
}

// ---------------------------------------------------------------- the oracle tests

macro_rules! oracle_tests {
    ($($case:ident),* $(,)?) => {
        $(
            mod $case {
                use super::{
                    check_group, check_status, engine, Derivatives, WITH_CLOSED_FORMS,
                };
                const NAME: &str = concat!("fit_", stringify!($case));
                #[test]
                fn analytic_converges() {
                    check_status(NAME, Derivatives::Analytic, WITH_CLOSED_FORMS);
                }
                #[test]
                fn analytic_estimates() {
                    check_group(NAME, "estimates", Derivatives::Analytic, WITH_CLOSED_FORMS);
                }
                #[test]
                fn analytic_residual_sum_of_squares() {
                    check_group(NAME, "wrss", Derivatives::Analytic, WITH_CLOSED_FORMS);
                }
                #[test]
                fn analytic_statistics() {
                    check_group(NAME, "statistics", Derivatives::Analytic, WITH_CLOSED_FORMS);
                }
                #[test]
                fn analytic_confidence_limits() {
                    check_group(NAME, "intervals", Derivatives::Analytic, WITH_CLOSED_FORMS);
                }
                #[test]
                fn analytic_information_criteria() {
                    check_group(NAME, "information_criteria", Derivatives::Analytic, WITH_CLOSED_FORMS);
                }
                #[test]
                fn analytic_secondary_parameters() {
                    check_group(NAME, "secondary", Derivatives::Analytic, WITH_CLOSED_FORMS);
                }
                #[test]
                fn forward_difference_converges() {
                    check_status(NAME, Derivatives::ForwardDifference, engine);
                }
            }
        )*
    };
}

oracle_tests! {
    infusion_uniform, infusion_inv_y, infusion_inv_y2, infusion_inv_yhat, infusion_inv_yhat2,
    zero_order_uniform, zero_order_inv_y, zero_order_inv_y2, zero_order_inv_yhat, zero_order_inv_yhat2,
    lag_uniform, lag_inv_y, lag_inv_y2, lag_inv_yhat, lag_inv_yhat2,
}

/// The engine as shipped (`run`, not the test-side `FitModel`) has to accept
/// `Derivatives::Analytic` for the model (FIT-JAC-02), converge on every case of it and reproduce
/// the R values in the seven groups of the `analytic_*` tests, at the same tolerances.
fn engine_has_closed_forms(prefix: &str) {
    let cases: Vec<String> = caladrius_testkit::list_fit_cases()
        .unwrap()
        .into_iter()
        .filter(|n| n.starts_with(prefix))
        .collect();
    assert_eq!(cases.len(), 5, "{cases:?}");
    for case in cases {
        check_status(&case, Derivatives::Analytic, engine);
        for group in [
            "estimates",
            "wrss",
            "statistics",
            "intervals",
            "information_criteria",
            "secondary",
        ] {
            check_group(&case, group, Derivatives::Analytic, engine);
        }
    }
}

#[test]
fn the_engine_has_closed_form_derivatives_for_pk1_iv_infusion() {
    engine_has_closed_forms("fit_infusion_");
}

#[test]
fn the_engine_has_closed_form_derivatives_for_pk1_oral_0() {
    engine_has_closed_forms("fit_zero_order_");
}

#[test]
fn the_engine_has_closed_form_derivatives_for_pk1_oral_1_lag() {
    engine_has_closed_forms("fit_lag_");
}

/// Guards the guard: every synthetic fit case of the oracle is run by a test above, and the
/// reference model ids are the ones of the catalogue.
#[test]
fn every_new_fit_case_has_tests() {
    let covered = [
        "infusion_uniform",
        "infusion_inv_y",
        "infusion_inv_y2",
        "infusion_inv_yhat",
        "infusion_inv_yhat2",
        "zero_order_uniform",
        "zero_order_inv_y",
        "zero_order_inv_y2",
        "zero_order_inv_yhat",
        "zero_order_inv_yhat2",
        "lag_uniform",
        "lag_inv_y",
        "lag_inv_y2",
        "lag_inv_yhat",
        "lag_inv_yhat2",
    ];
    let new: Vec<String> = caladrius_testkit::list_fit_cases()
        .unwrap()
        .into_iter()
        .filter(|n| {
            ["fit_infusion_", "fit_zero_order_", "fit_lag_"]
                .iter()
                .any(|p| n.starts_with(p))
        })
        .collect();
    assert_eq!(new.len(), covered.len(), "{new:?}");
    for name in new {
        let short = name.strip_prefix("fit_").unwrap();
        assert!(covered.contains(&short), "{name} has no test");
        let case = caladrius_testkit::load_fit_case(&name).unwrap();
        let expected_model = if short.starts_with("infusion") {
            "pk1.iv_infusion"
        } else if short.starts_with("zero_order") {
            "pk1.oral_0"
        } else {
            "pk1.oral_1_lag"
        };
        assert_eq!(case.model, expected_model, "{name}");
        // The two input-duration models need `dur` fixed; the lag model fits everything.
        assert_eq!(
            case.fixed.contains_key("dur"),
            expected_model != "pk1.oral_1_lag"
        );
        assert_eq!(case.subjects.len(), 6, "{name}");
    }
}
